### PR TITLE
Upgrade clor to turbocolor

### PR DESCRIPTION
**Pull request by jorgebucaran**
Hi @stripedpajamas! I deprecated clor and rebranded it some time ago. This PR upgrades you to its latest and [faster](https://github.com/jorgebucaran/turbocolor/tree/master/bench#benchmarks) incarnation: turbocolor. In turbocolor, style methods return strings, so we don't need to coerce everything to a string.

Let me know if this looks good to you. Cheers! 👋

### CODE REVIEW

**Comment by stripedpajamas** [comment]
wow thank you!! that cleans things up so much :heart_eyes:

**Comment by jorgebucaran** [comment]
@stripedpajamas Awesome! Will you be publishing a new version too?

**Comment by stripedpajamas** [comment]
I will be-- soon 😄

**Comment by jorgebucaran** [comment]
Yay! 🎉

**Pull request merged**
